
# https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

Space       script-message mpv.net play-pause 
F11         playlist-prev; set pause no #menu: Navigate > Previous File
F12         playlist-next; set pause no #menu: Navigate > Next File
Right       seek  5                #menu: Navigate > Jump 5 sec forward
Left        seek -5                #menu: Navigate > Jump 5 sec backward
i       script-message mpv.net show-info            #menu: View > Show File/Stream Info
_       playlist-shuffle                            #menu: Tools > Shuffle Playlist
Ctrl+h  cycle-values hwdec auto no                  #menu: Tools > Toggle Hardware Decoding
q       quit                            #menu: Tools > Exit Watch Later
Play          cycle pause
Pause         cycle pause
Stop          stop
Wheel_Left    add volume -2 
Wheel_Right   add volume  2 
Prev          playlist-prev
Next          playlist-next
D add sub-scale +0.1
S add sub-scale -0.1
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5


