hwdec=vaapi
hwdec=yes
--volume=50
audio-file-auto=exact
cache=yes
demuxer-max-bytes=123400KiB
demuxer-readahead-secs=20
--sub-auto=exact
slang=eng
alang=jpy,jp
save-position-on-quit=yes
#loop-playlist=inf
profile=720p
#[1080p]
#ytdl-format=bestvideo[height<=?1080]+bestaudio/best
# Use the explicit path to your exported cookie file
ytdl-raw-options-append=cookies=/home/aditya/.config/mpv/cookies.txt
ytdl-raw-options-append=mark-watched=
ytdl-raw-options-append=user-agen"Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0"
sub-auto=exact
ytdl-raw-options=ignore-config=,sub-format=en,write-sub=
sub-font-size=26
slang=en
screenshot-dir=~/Pictures/MPV-Screenshots
[1080p]
ytdl-format=bestvideo[height<=?1080]+bestaudio/best

[720p]
ytdl-format=bestvideo[height<=?720]+bestaudio/best

[480p]
ytdl-format=bestvideo[height<=?480]+bestaudio/best

[360p]
ytdl-format=bestvideo[height<=?360]+bestaudio/best

#[360p]
#ytdl-format=bestvideo[height<=?360]+bestaudio/best

