music_directory		"~/Music/"
bind_to_address "any"
#
playlist_directory		"~/.local/share/mpd/playlists"
db_file			"~/.local/share/mpd/database"
log_file			"syslog"
pid_file			"~/.local/share/mpd/pid"
state_file			"~/.local/share/mpd/state"
sticker_file			"~/.local/share/mpd/sticker.sql"
auto_update	"yes"
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
# FIFO visualizer in ncmpcpp
audio_output {
    type                "fifo"
    name                "mpd_fifo"
    path                "/tmp/mpd.fifo"
    format              "44100:16:2"
}
audio_output {
    type        "httpd"
    name        "MyRadio"
#using mp3 format for compatibility
#I use 8000 here, but you can use whatever port you like                 
    port        "8000"                 
    always_on   "yes"
    replay_gain_handler "software"
    tags        "yes"
# do not define bitrate if quality is defined
    bitrate     "64"            
    format      "22050:16:1"
}
